/*
   dnsconfig.js: dnscontrol configuration generated by `dnscontrol init`.
*/

// Providers:

var REG_NONE = NewRegistrar("none_primary");
var DNS_NETNOD = NewDnsProvider("netnod_primary");

// Domains:

D("k8s.signed.zone", REG_NONE, DnsProvider(DNS_NETNOD),
    A("@", "1.2.3.4")
);

